Issue 12155: 1: Customer projects merges default resources with their own: Modified imcms.war artifact packaging - resource files are copied under WEB-INF/classes instead of archiving into WEB-INF/lib/imcms-classes.jar.
2: java.lang.NoClassDefFoundError: org/springframework/web/servlet/handler/AbstractUrlHandlerMapping$PathExposingHandlerInterceptor on startup

Included missing dependency

git-svn-id: https://svn.imcode.com/imcode/imcms/branches/alpha23_almedalen@27975 bd66a97b-2aff-0310-9095-89ca5cabf5a6